### ISSUE TITLE
v3.0.0 - device error (works with 2.14.2)

### ISSUE THREAD

**Issue by thechris1992** [bwp91/homebridge-govee#62] opened 2021-04-06 10:11 UTC
### What issue do you have? Please be as thorough and explicit as possible.
Device not response with update homebridge-govee v3.0.0

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 
HB with config UI (homebridge-config-ui-x v4.41.0)
Node.js Version | v14.16.0
NPM Version | v6.14.11

* Which version of Homebridge/HOOBS do you have?
v1.3.4

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
with homebridge-govee v2.14.2 on / off, brightness etc works great

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee Model | H6104

### Please paste any relevant logs below.
[Govee] [Ambient Light] could not be updated as device cannot currently be controlled at deviceLightColour.internalOnOffUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/device/light-colour.js:171:15).

**Comment by thechris1992** [comment] 2021-04-06 10:22
after Update NPM to 7.8.0 i got the same error
[Govee] [Ambient Light] could not be updated as device cannot currently be controlled at deviceLightColour.internalOnOffUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/device/light-colour.js:171:15).

**Comment by bwp91** [comment] 2021-04-06 10:28
Hi @thechris1992 
Could you turn on debug mode and copy and paste some log lines, the ones that say “receiving update…”
They should appear each 15 seconds or so

**Comment by thechris1992** [comment] 2021-04-06 14:42
[06/04/2021, 16:40:26] [Govee] [Ambient Light] could not be updated as device cannot currently be controlled at deviceLightColour.internalOnOffUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/device/light-colour.js:171:15).

and new with extended logging:
[06/04/2021, 16:40:46] [Govee] [Ambient Light] skipping sync as device status not retrievable.




no network changes. 
if i downgrade to 2.14.2 it works

**Comment by bwp91** [comment] 2021-04-06 15:21
Govee reports three device status flags to the plugin

* **retrievable** whether the current device status can be retrieved
* **controllable** whether the device can be controlled at that moment, and
* **online** whether the device is currently connected to wifi

The plugin syncs the device status every 15 seconds and if the **retrievable** flag is reported as false, then the sync will skip with the message as you have received:

```
[Ambient Light] skipping sync as device status not retrievable.
```

The sync process has not changed between versions 2 and 3 of the plugin... so in either version if the device is not **retrievable** then you will see this message.

With regards to the other two flags, **controllable** and **online**, this is where there is a change between v2 and v3 of the plugin.

In both versions, if **controllable** is false, then controlling the device through HomeKit will fail, with the message

```
[Ambient Light] could not be updated as device cannot currently be controlled
```

In v2, the plugin did not check the **online** status of the device and would send updates when the device was controlled through HomeKit, and the device would not update. I was receiving a numerous amount of issues on here and on discord with users wondering why the device wasn't updating - due to the **online** status being false.

So in v3 the plugin now checks the **online** status of the device when sending a command, and if **online** is false then the plugin will raise the error - the "no response" message in Home app, and the 

```
[Ambient Light] could not be updated as device cannot currently be controlled
```

line in the Homebridge log.

Please update to v3 of the plugin again, with plugin debug ON and see if device control works. There maybe something in the code that I have missed, but in these circumstances (and from what your log messages are saying) it's most likely that your device is not connected to wifi when you try and control the device.

Let me know how you get on and if necessary I can look into this further.

Hope this explanation of how the plugin works has helped, in particular the differences between both plugin versions.

**Comment by thechris1992** [comment] 2021-04-06 16:08
The Groove app displays that the Device is online with BT and wifi (blue icons)

with the old version and logging on
[06/04/2021, 18:03:19] [Govee] [Ambient Light] skipping sync as device status not retrievable.
[06/04/2021, 18:03:31] [Govee] [Ambient Light] is offline - command will be sent but device may not react.
[06/04/2021, 18:03:31] [Govee] [Ambient Light] sending update {"name":"turn","value":"on"}.
[06/04/2021, 18:03:31] [Govee] [Ambient Light] current state [on].
[06/04/2021, 18:03:34] [Govee] [Ambient Light] skipping sync as device status not retrievable.
[06/04/2021, 18:03:36] [Govee] [Ambient Light] is offline - command will be sent but device may not react.
[06/04/2021, 18:03:36] [Govee] [Ambient Light] sending update {"name":"turn","value":"off"}.
[06/04/2021, 18:03:37] [Govee] [Ambient Light] current state [off].


But it is online and can be controlled over HK + the App.
(like u explain)

In the "My Devices" section the device is 
Cloud Status | Offline



I can ping the device from my pi.
Is there any url wo must be opend? (i am running pi hole, bur never seen a blocked url from this device)



Device Name	Ambient Light	
Cloud Status	 Offline	
Govee Device ID		
Retrievable	No	
Controllable	Yes	
Govee Model	H6104	
Supported Commands	turn, brightness, color, colorTem

**Comment by bwp91** [comment] 2021-04-06 16:23
So it seems the Govee API is reporting the device as un**controllable**, un**retrievable** and not **online** even though in fact it is online. Perhaps the pi hole is limiting some communication between the device and the API server? (which could be a separate link as opposed to between the device and the Govee app.

Could I message you on discord?
https://discord.gg/cMGhNtZ3tW

I will look into a configuration option to override the offline check and send commands to the device and it would be useful if you were able to test this.

I don't particularly want to revert the changes I made with regards to the HomeKit error if the device is marked as offline, as a lot of users are unaware that their devices can drop wifi connection and hence are uncontrollable by the plugin.

**Comment by bwp91** [comment] 2021-04-06 17:24
The next version of the plugin will include a configuration option to "force" updates to Govee even if the device is reported as offline.

This is available now in the current beta version of the plugin.

As to why the device is being reported as offline even though it is in fact online... who knows... but the `forceUpdates` configuration option will function as a workaround for this situation.

**Comment by RaduMC** [comment] 2021-04-07 18:17
Just to let you know, I have the same issue, using H6104 with Homebridge v1.3.4 and plugin v3.0.0
So it's not an isolated incident, and it happened right after I updated to V3.

The only difference for me is I can no longer control the device from HK; only from the Govee app (over Wifi, not BT).
Apple Home shows "No response".
How can I test connectivity with the API server? Could you please share the IP or URI?

[4/7/2021, 9:14:07 PM] [Govee] [Govee TV LED] could not be updated as device cannot currently be controlled at deviceLightColour.internalBrightnessUpdate (/usr/lib/node_modules/homebridge-govee/lib/device/light-colour.js:230:15).
[4/7/2021, 9:14:07 PM] [Govee] [Govee TV LED] could not be updated as device cannot currently be controlled at deviceLightColour.internalOnOffUpdate (/usr/lib/node_modules/homebridge-govee/lib/device/light-colour.js:171:15).
[4/7/2021, 9:14:08 PM] [Govee] [Govee TV LED] skipping sync as device status not retrievable.
[4/7/2021, 9:14:23 PM] [Govee] [Govee TV LED] skipping sync as device status not retrievable.

**Comment by bwp91** [comment] 2021-04-07 19:09
@RaduMC 
For now, please enable the 'Force Updates' option I added in the latest version, does this help with controlling the device?

**Comment by RaduMC** [comment] 2021-04-07 19:34
Confirmed it works with Force updates. Thanks for everything!

**Comment by bwp91** [comment] 2021-04-07 21:02
Seems to be in some situations the govee api is incorrectly reporting devices as offline 🙄
in general the api is difficult to work with i hope they improve it in the future!

**Closed as completed** 2021-04-09 05:44 UTC
Labels: complete

**Comment by RaduMC** [comment] 2021-05-01 05:22
I just upgraded my H6104 to the new H6199.
Guess what, the device is online, no issues.

I think either Govee changed something in the API between new and old devices, or they simply deactivated some functions for old devices.

**Comment by jsonhuntrods** [comment] 2021-09-13 04:18
Just to document here, I have the H6159 Light Strip, and I get this no response error. 

```
[12/09/2021, 23:15:36] [Govee] [TV Backlight] has been reported [offline] via API, so update may or may not be successful.
[12/09/2021, 23:15:36] [Govee] [TV Backlight] [AWS] sending update {"msg":{"accountTopic":"GA/99f21c09f57f2152df09202b66231cd0","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631506536215000","type":1}}.
[12/09/2021, 23:15:36] [Govee] [TV Backlight] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1029:17.
[12/09/2021, 23:15:36] [Govee] [TV Backlight] [AWS] message event [GD/6ac47338672ebeb76317b41e34e0060c {"msg":{"accountTopic":"GA/99f21c09f57f2152df09202b66231cd0","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631506536215000","type":1}}].
[12/09/2021, 23:15:36] [Govee] [TV Backlight] [AWS] receiving update [{"accountTopic":"GA/99f21c09f57f2152df09202b66231cd0","cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1631506536215000","type":1,"source":"AWS"}].
[12/09/2021, 23:15:36] [Govee] [TV Backlight] current state [on].
```

However, the device works fine in HomeKit, the only downside is Siri will always say the the device isn't responding after using it in a command, even if the command is successful.

**Comment by bwp91** [comment] 2021-09-13 05:49
Hi @jasonhuntrods-toast 

Do you have your govee api key entered in the configuration?

**Comment by jsonhuntrods** [comment] 2021-09-13 13:40
@bwp91 I don't but I wondered if that was necessary... Sent in a message to get one and will report back if I get one.

**Comment by jsonhuntrods** [comment] 2021-09-13 13:45
@bwp91 Actually got the key already, and no more issues after using the key! 🥳 

The readme says:
```
requires your Govee API key for certain light models
```

but I guess since my light strip worked fine, that wasn't the issue.

Anyway great plugin and hopefully this will leave some documentation if people have a similar problem.

**Comment by bwp91** [comment] 2021-09-13 15:41
@jasonhuntrods-toast 

Different connection types require different credentials.

The API connection method (what the plugin used from the beginning) uses the API key. However the API can often be slow (but sure) to respond.

The AWS connection method (newer connection method) uses the username and password. This connection method can be much quicker, but seems to rely on the device being online at the time the command is sent. Otherwise the attempt is lost. Also using this connection method, the plugin doesn’t actually know if the command has been received or not. The plugin does not consider a home app device update successful if just the AWS is sent.

So when a device update is sent, it is sent via AWS and API (AWS almost like a faster bonus, but fallback to the API anyway).

In your case where you just had your username and password, only the AWS was being used, and because your API token wasn’t present, the API wasn’t being used, so the command was failing. Even though the command was potentially working via AWS.

i feel like i’m explaining in circles, but maybe that makes sense!
