### ISSUE TITLE
H5151 Gateway and H5100 Therm/Hygrometers

### ISSUE THREAD

**Issue by rmaes4** [bwp91/homebridge-govee#225] opened 2022-03-14 01:00 UTC
I see that bluetooth devices are not supported but the Gateway uses wifi. Can support be added for these sensors/gateway? Right now in the logs I am getting "bluetooth sensor not supported by this plugin, see " but these operate over Wifi.

**Comment by bwp91** [comment] 2022-04-16 13:41
Hi @rmaes4 

Apologies I'm a bit behind on all these govee issues right now! Getting through them slowly.

I never realised that a wifi gateway existed for these sensors.

When you start the plugin, does it show any info about the H5151 being not supported?

**Comment by rmaes4** [comment] 2022-04-18 02:29
@bwp91 

No worries, I understand being busy completely.

These are the logs I get when starting the plugin.

```
[17/04/2022, 21:24:42] [Govee] [Bed Therm. (3)] bluetooth sensor not supported by this plugin, see https://bit.ly/hb-plugin-govee
[17/04/2022, 21:24:42] [Govee] [Window Therm. (2)] bluetooth sensor not supported by this plugin, see https://bit.ly/hb-plugin-govee
[17/04/2022, 21:24:42] [Govee] [Dresser Therm. (1)] bluetooth sensor not supported by this plugin, see https://bit.ly/hb-plugin-govee
```

It doesn't seem there are any logs pertaining to the H5151 gateway, only the H5100 sensors.

**Comment by jaalfaro** [comment] 2022-06-08 15:38
Looks like there is a new API at https://app2.govee.com/app/v1/gateways to get the gateway H5151
Then from there, will likely need a new thermo class for gateway, so something like ThermoGateway and when you discover H5100, have to look and see if its part of the gateway or not.  I've only glanced at your code, but, I think because the H5100 is tagged as BLE, it now is BLE over gateway.  Should be fun to handle.

**Comment by coreyjackwilson** [comment] 2022-06-29 01:44
Upvote on this. Would be nice to have!

**Comment by metalcated** [comment] 2022-07-02 03:32
Looking forward to this myself. I just picked this H5151 up and thought it would work. lol. Glad to see someone supporting this though. Thanks for your hard work!

**Comment by bwp91** [comment] 2022-07-02 13:56
Can anyone update to the new beta 5.2.1-beta.3 of the plugin? I have re-enabled these bluetooth sensors to show.

Maybe their current temperature/humidity values that the plugin collects about these devices is automatically updated by the gateway. This is what I am hoping!

Instructions for beta installation if needed:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by metalcated** [comment] 2022-07-02 14:52
> Can anyone update to the new beta 5.2.1-beta.3 of the plugin? I have re-enabled these bluetooth sensors to show.
> 
> Maybe their current temperature/humidity values that the plugin collects about these devices is automatically updated by the gateway. This is what I am hoping!
> 
> Instructions for beta installation if needed: https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

Awesome!! Working! I have my temps and humidity showing up now! Thanks dude!

**Comment by bwp91** [comment] 2022-07-02 15:10
Do the values update over time if you don’t connect your phone to the sensors within the govee app?

**Comment by metalcated** [comment] 2022-07-03 12:31
> Do the values update over time if you don’t connect your phone to the sensors within the govee app?

I’ll check throughout the day today. At the moment the values in the app and HomeKit are the same (rounded up and down to the nearest tenth - I assume that’s by design or HomeKit doing it).

**Comment by LiamSx45** [comment] 2022-07-05 18:55
Is there any way to change the temperature from C to F?

**Comment by metalcated** [comment] 2022-07-06 03:20
> > Do the values update over time if you don’t connect your phone to the sensors within the govee app?
> 
> I’ll check throughout the day today. At the moment the values in the app and HomeKit are the same (rounded up and down to the nearest tenth - I assume that’s by design or HomeKit doing it).

Looks good on my end, values are updating.

**Comment by bwp91** [comment] 2022-07-08 05:19
> Is there any way to change the temperature from C to F?

In the settings app on your iphone, go to Language & Region -> Temperature Unit -> and choose F.

This should show the values in the home app as fahrenheit

**Comment by bwp91** [comment] 2022-10-10 18:28
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Closed as completed by bwp91** 2022-10-10 18:28 UTC
Labels: don't close
