### ISSUE TITLE
Govee 5080 Plugs not responding via HomeKit

### ISSUE THREAD

**Issue by sskamboj** [bwp91/homebridge-govee#359] opened 2022-11-18 14:57 UTC
### What issue do you have? Please be as thorough and explicit as possible.
As of about two weeks ago, the Govee plugs I have, model 5080, powering my bedroom lights and christmas tree are not responding to HomeKit events. The plugs still work through the Govee App, but HomeKit response has stopped. My TV lights, however, still work with HomeKit without issue. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge 1.5.1 

* Which version of Homebridge/HOOBS do you have?
1.5.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
* Node.js v. 16.16.0 running on Bonjour
* homebridge-config-ui-x v4.50.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Homebridge govee plugin version homebridge-govee v7.1.5

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Two Govee plugs, modelH5080, is it related to the node.js error below? 

### Please paste any relevant logs below.

[11/18/2022, 8:46:01 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/18/2022, 8:46:06 AM] [HB Supervisor] Restarting Homebridge...
[11/18/2022, 8:46:06 AM] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/18/2022, 8:46:06 AM] [HB Supervisor] Started Homebridge v1.5.1 with PID: 51249
[11/18/2022, 8:46:06 AM] Loaded config.json with 0 accessories and 2 platforms.
[11/18/2022, 8:46:06 AM] Loaded 3 cached accessories from cachedAccessories.
[11/18/2022, 8:46:06 AM] ---
[11/18/2022, 8:46:07 AM] Loaded plugin: homebridge-config-ui-x@4.50.2
[11/18/2022, 8:46:07 AM] Registering platform 'homebridge-config-ui-x.config'
[11/18/2022, 8:46:07 AM] ---
[11/18/2022, 8:46:07 AM] The plugin "homebridge-govee" requires Node.js version of ^14.21.1 || ^16.18.1 || ^18.12.1 which does not satisfy the current Node.js version of v16.16.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[11/18/2022, 8:46:07 AM] Loaded plugin: homebridge-govee@7.1.5
[11/18/2022, 8:46:07 AM] Registering platform 'homebridge-govee.Govee'
[11/18/2022, 8:46:07 AM] ---
[11/18/2022, 8:46:07 AM] Loading 2 platforms...
[11/18/2022, 8:46:07 AM] [Govee] Initializing Govee platform...
[11/18/2022, 8:46:07 AM] [Govee] Initialising plugin v7.1.5 | System darwin | Node v16.16.0 | HB v1.5.1 | HAPNodeJS v0.10.4...
[11/18/2022, 8:46:07 AM] [Govee] Plugin initialised. Setting up accessories....
Setup Payload:
X-HM://0024PKRRKSFOS
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 749-86-128 │     
    └────────────┘     
                       
[11/18/2022, 8:46:07 AM] Homebridge v1.5.1 (HAP v0.10.4) (Homebridge 5483) is running on port 51649.
[11/18/2022, 8:46:09 AM] [Govee] [LAN] client enabled and found 0 device(s).
[11/18/2022, 8:46:09 AM] [Govee] [HTTP] client enabled and found 3 device(s).
[11/18/2022, 8:46:09 AM] [Govee] [AWS] client enabled.
[11/18/2022, 8:46:10 AM] [Govee] [API] client enabled and found 3 device(s).
[11/18/2022, 8:46:10 AM] [Govee] [BLE] disabling client as not supported on mac devices.
[11/18/2022, 8:46:10 AM] [Govee] [Tree] initialising with options {"showAs":"outlet"}.
[11/18/2022, 8:46:10 AM] [Govee] [Tree] initialised with id [1E:A7:D4:AD:FC:3C:DB:62] [H5080].
[11/18/2022, 8:46:10 AM] [Govee] [Bedroom Lights] initialising with options {"showAs":"outlet"}.
[11/18/2022, 8:46:10 AM] [Govee] [Bedroom Lights] initialised with id [44:41:D4:AD:FC:4A:19:86] [H5080].
[11/18/2022, 8:46:10 AM] [Govee] [TV Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[11/18/2022, 8:46:10 AM] [Govee] [TV Lights] initialised with id [AD:3B:A4:C1:38:9A:7B:EF] [H6141].
[11/18/2022, 8:46:10 AM] [Govee] [TV Lights] has been reported [online].
[11/18/2022, 8:46:10 AM] [Govee] [Tree] has been reported [online].
[11/18/2022, 8:46:10 AM] [Govee] [Bedroom Lights] has been reported [online].
[11/18/2022, 8:46:12 AM] [Govee] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
[11/18/2022, 8:46:25 AM] [Govee] [Tree] current state [on].
[11/18/2022, 8:46:30 AM] [Govee] [Tree] current state [off].
[11/18/2022, 8:48:14 AM] [Govee] [Tree] current state [on].
[11/18/2022, 8:48:17 AM] [Govee] [Tree] current state [off].
```

```

**Comment by bwp91** [comment] 2022-11-19 17:47
Closing as duplicate of
https://github.com/bwp91/homebridge-govee/issues/358
Something I am aware of and working on 👍🏻

**Closed as completed by bwp91** 2022-11-19 17:47 UTC
