### ISSUE TITLE
Govee TV Lights Not Responsive

### ISSUE THREAD

**Issue by jeanofthedead** [bwp91/homebridge-govee#11] opened 2020-10-27 17:06 UTC
**What issue do you have? Please be as thorough and explicit as possible.**
I have the Govee TV Lights (model H6104) and Homebridge reports this error when I power cycle them in the Home App:

> [TV Lights] could not be updated and its status will be reverted soon. Error: Request failed with status code 400.

...

**Details of your setup.**
Do you use Homebridge or HOOBS?
Homebridge
...

Which version of Homebridge/HOOBS do you have?
v1.1.6
...

Which version of this plugin (homebridge-govee) do you have?
v2.0.5
...

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

...

**Comment by bwp91** [comment] 2020-10-27 17:14
Hi,
Please from the plugin settings can you turn on Debug Logging and Request & Response Logging.
Then additional information will be added to the homebridge logs, hopefully indicating a more specific error.
Thanks

**Comment by jeanofthedead** [comment] 2020-10-27 17:29
Sure thing:

> [10/27/2020, 10:28:28] [Govee]  → [TV Lights] status could not be updated as current status could not be retrieved.
> [10/27/2020, 10:28:28] [Govee] [updateDevice()] HTTP Request. This message is yellow for clarity:
> {
>   "device": "9B:09:78:9C:E7:0A:46:BC",
>   "model": "H6104",
>   "cmd": {
>     "name": "turn",
>     "value": "off"
>   }
> }

After switching the power state, it seems to refresh and function just fine, however. It just seems to not be able to sense the power state initially.

**Comment by jeanofthedead** [comment] 2020-10-27 17:30
I am now getting this error:

> [10/27/2020, 10:28:44] [Govee]  → [TV Lights] status could not be updated as current status could not be retrieved.

**Comment by bwp91** [comment] 2020-10-27 17:39
Could be that the light strip is in a mode that the plugin doesn’t support. which mode are you using when you get these errors?
Without a lengthy set of logs it’s difficult to pinpoint what the issue is!

**Comment by jeanofthedead** [comment] 2020-10-27 17:59
That could very well be. The mode for these TV Lights w/ camera is set to Video (Part or All as options).

**Comment by bwp91** [comment] 2020-10-27 18:14
The `current status could not be retrieved` is a specific error that is shown when govee “says” it can’t get the status.
I genuinely believe your strip is in a mode that isn’t supported by the API. Frustrating I know, but with this plugin I am limited by the capabilities of the API.

**Comment by jeanofthedead** [comment] 2020-10-27 18:43
No worries- I appreciate you looking into it. Hopefully Govee will expand their API in the future. All of my other Govee models are working great, thanks to you. Feel free to close this issue. Cheers.

**Comment by bwp91** [comment] 2020-10-27 18:52
Thanks @jeanofthedead, glad in all other cases the plugin is working well.
Will close this due to this being an “issue” out of my control, due to limitations of the Govee API.

**Closed as completed by bwp91** 2020-10-27 18:52 UTC
